Traceback (most recent call last):
  File "/Users/hepting/Sites/dhhepting.github.io/script/asgn_moddate.py", line 50, in <module>
    for line in f:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4431: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/hepting/Sites/dhhepting.github.io/script/asgn_moddate.py", line 50, in <module>
    for line in f:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4431: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/hepting/Sites/dhhepting.github.io/script/asgn_moddate.py", line 50, in <module>
    for line in f:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4431: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/hepting/Sites/dhhepting.github.io/script/asgn_moddate.py", line 50, in <module>
    for line in f:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4431: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/hepting/Sites/dhhepting.github.io/script/asgn_moddate.py", line 50, in <module>
    for line in f:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4431: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/hepting/Sites/dhhepting.github.io/script/asgn_moddate.py", line 50, in <module>
    for line in f:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4431: ordinal not in range(128)
Traceback (most recent call last):
  File "/Users/hepting/Sites/dhhepting.github.io/script/asgn_moddate.py", line 50, in <module>
    for line in f:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4431: ordinal not in range(128)
